// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTWtZI_SIJc5Dyw5jEGttncDCb-9kWtZo',
    appId: '1:628682113871:web:26b31a34dce1663b897b3a',
    messagingSenderId: '628682113871',
    projectId: 'eduxchange-f725c',
    authDomain: 'eduxchange-f725c.firebaseapp.com',
    storageBucket: 'eduxchange-f725c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHWwh6JWpgvCKfAXjW1VSsNyq3vX5i4so',
    appId: '1:628682113871:android:87b5a33ad75cdf01897b3a',
    messagingSenderId: '628682113871',
    projectId: 'eduxchange-f725c',
    storageBucket: 'eduxchange-f725c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK8rhVNhCVIIL2uxYhfGdXx7zAHWNLJsY',
    appId: '1:628682113871:ios:61acdb7e4ff66af9897b3a',
    messagingSenderId: '628682113871',
    projectId: 'eduxchange-f725c',
    storageBucket: 'eduxchange-f725c.firebasestorage.app',
    iosBundleId: 'com.example.eduXchange',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK8rhVNhCVIIL2uxYhfGdXx7zAHWNLJsY',
    appId: '1:628682113871:ios:61acdb7e4ff66af9897b3a',
    messagingSenderId: '628682113871',
    projectId: 'eduxchange-f725c',
    storageBucket: 'eduxchange-f725c.firebasestorage.app',
    iosBundleId: 'com.example.eduXchange',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTWtZI_SIJc5Dyw5jEGttncDCb-9kWtZo',
    appId: '1:628682113871:web:8cf06f5d923fa11f897b3a',
    messagingSenderId: '628682113871',
    projectId: 'eduxchange-f725c',
    authDomain: 'eduxchange-f725c.firebaseapp.com',
    storageBucket: 'eduxchange-f725c.firebasestorage.app',
  );
}
